services:
  postgres:
    image: pgvector/pgvector:pg14
    container_name: ai-foundations
    ports:
      - 5432:5432
    volumes:
      - ~/dev/database/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=ai-foundations
